apiVersion: v1
kind: Service
metadata:
  name: restaurant-management-service
  namespace: restaurant-management
spec:
  selector:
    app: restaurant-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
